config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'index/index'
  resources :products

  root 'index#index'

  # === Carrinho
  get 'cart' => 'cart#index'
  post 'cart/add/:id' => 'cart#add_item', as: :add_item_to_cart
  post 'cart/remove/:id' => 'cart#remove_item', as: :remove_item_from_cart
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: products
#
#  id                  :bigint(8)        not null, primary key
#  name                :string(255)
#  image               :string(255)
#  description         :text(65535)
#  tension             :integer
#  stock               :integer
#  value               :float(24)
#  discount            :float(24)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  product_category_id :integer
#

class Product < ApplicationRecord
  include ActionView::Helpers::NumberHelper
  has_one_attached :image
  belongs_to :product_category

  def value_reais
    "R$ #{number_with_precision value, precision: 2, separator: ','}"
  end

  def value_discounted_reais
    "R$ #{number_with_precision (value - discount), precision: 2, separator: ','}"
  end

  def category
    product_category
  end
end

app/models/product_category.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: product_categories
#
#  id         :bigint(8)        not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ProductCategory < ApplicationRecord
  has_many :products
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cart

  private

  def set_cart
    session[:cart] ||= []
    @cart = session[:cart]
  end
end

app/controllers/cart_controller.rb
# frozen_string_literal: true

class CartController < ApplicationController
  def index
    @items = Product.find(@cart)
  end

  def add_item
    @cart << params[:id] if Product.exists? params[:id]

    redirect_to cart_path
  end

  def remove_item
    @cart.delete params[:id]

    redirect_to cart_path
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @products = params[:category] ? Product.where(product_category_id: params[:category]).all : Product.all
    @categories = ProductCategory.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
    @categories = ProductCategory.all
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :image, :description, :tension, :stock, :value, :discount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<h1> Carrinho </h1>
<% @items.each do |item| %>
  <p>
    <%= item.name %>
    <%= link_to "Remover", remove_item_from_cart_path(item.id), method: :post %>
  </p>
<% end %>

app/views/index/_best_seller.html.erb
<aside data-grid="best-seller">
  <div class="panel">
    <div class="panel-title">
      <h3>Mais vendidos</h3>
    </div>
    <ul class="list-unstyled panel-list">
      <li>
        <a href="#" class="no-decoration small-scale">Marcenaria</a>
      </li>
      <li>
        <a href="#" class="no-decoration small-scale">Jardinagem</a>
      </li>
      <li>
        <a href="#" class="no-decoration small-scale">Limpeza</a>
      </li>
      <li>
        <a href="#" class="no-decoration small-scale">Escritório</a>
      </li>
      <li>
        <a href="#" class="no-decoration small-scale">Mecânica</a>
      </li>
      <li>
        <a href="#" class="no-decoration small-scale">Outros</a>
      </li>
    </ul>
  </div>
</aside>

app/views/index/_categories.html.erb
<nav class="" data-grid="categories">
  <div class="panel">
    <div class="panel-title">
      <h3>Categorias</h3>
    </div>
    <ul class="list-unstyled panel-list">
      <% @categories.each do |category| %>
        <li>
          <a href="/?category=<%= category.id %>" class="no-decoration small-scale">
            <%= category.name %>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="search-field">
    <input type="text">
    <button type="button" name="button">OK</button>
  </div>
</nav>

app/views/index/_main.html.erb
<main data-grid="main">
  <div class="fl-block breadcrumb text-center">
    Lista de produtos
  </div>
  <!-- <h3 class="font-weight-normal">Lista de produtos</h3> -->

  <div class="products">
    <ul class="list-unstyled products-list">
      <% @products.each do |product| %>
        <li class="product-item">
          <div class="product-image">
            <% if product.image.attached? %>
              <%= image_tag product.image %>
            <% else %>
              <%= image_tag 'default-image.png' %>
            <% end %>
          </div>
          <%= link_to product, class: 'product-footer no-decoration' do %>
            <div class="product-name">
              <%= product.name %>
            </div>
            <div class="product-price">
              <%= product.value_reais %>
            </div>
          <% end %>
        </li>
      <% end %>
      <% if @products.empty? %>
        <p class="text-center">
          Nenhum produto encontrado :(
        </p>
      <% end %>
    </ul>
  </div>
</main>

app/views/index/index.html.erb
<div class="index-main">
  <div class="index-grid container">

    <%= render 'categories' %>

    <%= render 'main' %>

    <%= render 'best_seller' %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentATool</title>
    <meta name="google" content="notranslate" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
  </head>

  <body>
    <%= render 'layouts/partials/nav' %>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->

    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_nav.html.erb
<header class="header-wrapper">
  <div class="main-header container">
    <div class="company-logo">
      <h1>
        <%= link_to 'Rent A Tool', root_path, class: 'no-decoration text-white' %>
      </h1>
    </div>

    <div class="cart-button">
      <a href="#" class="small-scale">
        <%= link_to cart_path do %>
          <i class="lnr lnr-cart"></i> Ver carrinho
        <% end %>
      </a>
    </div>

    <nav class="navigation">
      <ul class="list-unstyled navigation-list">
        <li class="navigation-item">
          <% if user_signed_in? %>
            <%= link_to 'Minha conta', edit_user_registration_path, class: 'small-scale' %>
          <% else %>
            <%= link_to 'Entrar', new_user_session_path, class: 'small-scale' %>
          <% end %>
        </li>
        <li class="navigation-item">
          <a href="#" class="small-scale">Programa de pontos</a>
        </li>
        <li class="navigation-item">
          <a href="#" class="small-scale">Consumo solidário</a>
        </li>
        <li class="navigation-item">
          <a href="#" class="small-scale">Quem somos</a>
        </li>
        <li class="navigation-item">
          <a href="#" class="small-scale">Ajuda</a>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Nome' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image, 'imagem' %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :description, 'Descrição' %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :tension, 'Tensão' %>
    <%= form.number_field :tension %>
  </div>

  <div class="field">
    <%= form.label :stock, 'Estoque' %>
    <%= form.number_field :stock %>
  </div>

  <div class="field">
    <%= form.label :value, 'Valor' %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :discount, 'Desconto' %>
    <%= form.text_field :discount %>
  </div>

  <div class="actions">
    <%= form.submit 'Enviar' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editando produto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Exibir', @product %> |
<%= link_to 'Voltar', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Tensão</th>
      <th>Estoque</th>
      <th>Valor</th>
      <th>Desconto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.tension %></td>
        <td><%= product.stock %></td>
        <td><%= product.value %></td>
        <td><%= product.discount %></td>
        <td><%= link_to 'Mostrar', product %></td>
        <td><%= link_to 'Editar', edit_product_path(product) %></td>
        <td><%= link_to 'Deletar', product, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo produto', new_product_path %>

app/views/products/new.html.erb
<h1>Novo produto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Voltar', products_path %>

app/views/products/show.html.erb
<div class="index-main">
  <div class="index-grid container">

  <%= render 'index/categories' %>

  <section>
    <div class="fl-block breadcrumb">
      Início > Produtos > <%= @product.category&.name %>
    </div>

    <div class="product-show fl-block">

    <div class="product-image">
      <% if @product.image.attached? %>
      <%= image_tag @product.image%>
      <% else %>
      <%= image_tag 'default-image' %>
      <% end %>
    </div>

    <div class="product-info">
      <h1 class="product-title">
        <%= @product.name %>
      </h1>

      <p class="product-description">
        <%= @product.description %>
      </p>

      <h3 class="product-value">
        <% if @product.discount&.positive? %>
        <small>
          <strike><%= @product.value_reais %></strike>
        </small>
        <%= @product.value_discounted_reais %>
        <% else %>
        <%= @product.value_reais %>
        <% end %>
      </h3>

      <% if @product.tension&.positive? %>
      <p>
        Tensão:
        <%= @product.tension %>
      </p>
      <% end %>

      <p>
        <% if @product.stock.positive? %>
        <%= @product.stock %> disponíveis
        <% else %>
        Sem estoque
        <% end %>
      </p>

      <div class="product-buttons">
        <%= link_to 'Adicionar ao carrinho', add_item_to_cart_path(@product.id), class: 'button success text-center',
            method: :post %>
      </div>

    </div>

  </div>
  </section>

  <%= render 'index/best_seller' %>

  </div>

</div>